#GATK CallableLoci
#Adjustments to options needed for each run:
#input bam, -iinput_bam
#input bai, -iinput_bai
#output files prefix, -ioutput_prefix
#set region/chromosome, -L 
#maximum coverage threshold (dependent on platform-- 2x mean depth), -maxDepth
#output path, --destination


#Illumina Mate Pair
#HG003 run , ran 8 min to 27 min
#Mean Depth of coverage was estimated using chr20. Mean depth of coverage (DP) was 14.  maxDepth adjusted to 28
#Did not run MT because GATKHC failed to run
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.1.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.1.bai -ioutput_prefix=HG003_1_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 1 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.2.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.2.bai -ioutput_prefix=HG003_2_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 2 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.3.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.3.bai -ioutput_prefix=HG003_3_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 3 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.4.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.4.bai -ioutput_prefix=HG003_4_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 4 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.5.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.5.bai -ioutput_prefix=HG003_5_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 5 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.6.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.6.bai -ioutput_prefix=HG003_6_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 6 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.7.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.7.bai -ioutput_prefix=HG003_7_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 7 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.8.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.8.bai -ioutput_prefix=HG003_8_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 8 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.9.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.9.bai -ioutput_prefix=HG003_9_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 9 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.10.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.10.bai -ioutput_prefix=HG003_10_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 10 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.11.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.11.bai -ioutput_prefix=HG003_11_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 11 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.12.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.12.bai -ioutput_prefix=HG003_12_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 12 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.13.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.13.bai -ioutput_prefix=HG003_13_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 13 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.14.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.14.bai -ioutput_prefix=HG003_14_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 14 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.15.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.15.bai -ioutput_prefix=HG003_15_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 15 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.16.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.16.bai -ioutput_prefix=HG003_16_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 16 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.17.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.17.bai -ioutput_prefix=HG003_17_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 17 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.18.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.18.bai -ioutput_prefix=HG003_18_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 18 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.19.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.19.bai -ioutput_prefix=HG003_19_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 19 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.20.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.20.bai -ioutput_prefix=HG003_20_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 20 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.21.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.21.bai -ioutput_prefix=HG003_21_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 21 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.22.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.22.bai -ioutput_prefix=HG003_22_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L 22 -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
#dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.MT.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.MT.bai -ioutput_prefix=HG003_MT_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L MT -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.X.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.X.bai -ioutput_prefix=HG003_X_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L X -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-callableloci-v3.5 -iinput_bam=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.Y.bam -iinput_bai=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.Y.bai -ioutput_prefix=HG003_Y_hg19_bwa_mem_IlmnMatePair_callableloci -iextra_options="-L Y -minDepth 20 -mmq 20 -maxDepth 28" --destination=/HG003/Illumina/Illumina_hg19_MatePair/CallableLoci_output/
