#To run GATK-tenotype-gvcfs to convert gvcf output to vcf
#Adjustments to options needed for each run:
#input "vcf", -ivcfs
#input .vcf.tbi, -ivcfs
#output vcf filename prefix, -iprefix
#output path, --destination

#Illumina MatePair Data
#HG005 run 7/26/16, ran 6-12 min
#MT was not run because no MT bam
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_1_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_1_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_1_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_2_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_2_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_2_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_3_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_3_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_3_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_4_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_4_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_4_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_5_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_5_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_5_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_6_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_6_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_6_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_7_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_7_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_7_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_8_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_8_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_8_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_9_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_9_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_9_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_10_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_10_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_10_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_11_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_11_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_11_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_12_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_12_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_12_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_13_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_13_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_13_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_14_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_14_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_14_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_15_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_15_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_15_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_16_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_16_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_16_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_17_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_17_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_17_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_18_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_18_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_18_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_19_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_19_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_19_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_20_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_20_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_20_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_21_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_21_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_21_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_22_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_22_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_22_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_X_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_X_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_X_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_Y_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG005_Y_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG005_Y_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG005/Illumina/Illumina_hg19_MatePair/GATKHC_output/
