#FreeBayes
#Adjustments to options needed for each run:
#input bam, -isorted_bam
#output vcf filename prefix, -ioutput_prefix
#set reference genome, -igenome_fastagz
#set chromosome for bamtools, -itargets_bed
#output path, --destination

#Illumina Mate Pair
#HG002 run 6/14/16, ran 17 min up to to ~1 hr 40min
#MT Failed
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.1.bam -ioutput_prefix=HG002_1_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/1.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.2.bam -ioutput_prefix=HG002_2_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/2.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.3.bam -ioutput_prefix=HG002_3_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/3.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.4.bam -ioutput_prefix=HG002_4_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/4.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.5.bam -ioutput_prefix=HG002_5_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/5.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.6.bam -ioutput_prefix=HG002_6_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/6.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.7.bam -ioutput_prefix=HG002_7_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/7.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.8.bam -ioutput_prefix=HG002_8_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/8.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.9.bam -ioutput_prefix=HG002_9_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/9.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.10.bam -ioutput_prefix=HG002_10_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/10.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.11.bam -ioutput_prefix=HG002_11_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/11.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.12.bam -ioutput_prefix=HG002_12_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/12.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.13.bam -ioutput_prefix=HG002_13_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/13.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.14.bam -ioutput_prefix=HG002_14_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/14.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.15.bam -ioutput_prefix=HG002_15_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/15.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.16.bam -ioutput_prefix=HG002_16_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/16.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.17.bam -ioutput_prefix=HG002_17_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/17.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.18.bam -ioutput_prefix=HG002_18_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/18.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.19.bam -ioutput_prefix=HG002_19_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/19.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.20.bam -ioutput_prefix=HG002_20_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/20.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.21.bam -ioutput_prefix=HG002_21_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/21.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.22.bam -ioutput_prefix=HG002_22_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/22.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.X.bam -ioutput_prefix=HG002_X_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/X.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.Y.bam -ioutput_prefix=HG002_Y_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/Y.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG002/Illumina/Illumina_hg19_MatePair/HG002.mate_pair.sorted.MT.bam -ioutput_prefix=HG002_MT_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/MT.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG002/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
