#To run GATK-tenotype-gvcfs to convert gvcf output to vcf
#Adjustments to options needed for each run:
#input "vcf", -ivcfs
#input .vcf.tbi, -ivcfs
#output vcf filename prefix, -iprefix
#output path, --destination

#Illumina MatePair Data
#HG003 run 7/5/16, ran 6-12 min
#MT was not run because it failed variant calling
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_1_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_1_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_1_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_2_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_2_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_2_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_3_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_3_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_3_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_4_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_4_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_4_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_5_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_5_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_5_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_6_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_6_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_6_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_7_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_7_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_7_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_8_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_8_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_8_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_9_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_9_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_9_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_10_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_10_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_10_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_11_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_11_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_11_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_12_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_12_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_12_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_13_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_13_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_13_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_14_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_14_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_14_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_15_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_15_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_15_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_16_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_16_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_16_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_17_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_17_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_17_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_18_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_18_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_18_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_19_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_19_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_19_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_20_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_20_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_20_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_21_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_21_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_21_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_22_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_22_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_22_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
#dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_MT_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_MT_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_MT_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_X_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_X_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_X_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
dx run -y GIAB:/Workflow/GATK_V3.5/gatk-genotype-gvcfs-v3.5 -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_Y_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz -ivcfs=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/HG003_Y_hg19_bwa_mem_IlmnMatePair_GATKHC_gvcf.vcf.gz.tbi -iprefix=HG003_Y_hg19_bwa_mem_IlmnMatePair_GATKHC --destination=/HG003/Illumina/Illumina_hg19_MatePair/GATKHC_output/
