#FreeBayes
#Adjustments to options needed for each run:
#input bam, -isorted_bam
#output vcf filename prefix, -ioutput_prefix
#set reference genome, -igenome_fastagz
#set chromosome for bamtools, -itargets_bed
#output path, --destination

#Illumina Mate Pair
#HG003 run 7/5/16, ran 15 min to 1 hr 14 min
#MT could not be 
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.1.bam -ioutput_prefix=HG003_1_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/1.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.2.bam -ioutput_prefix=HG003_2_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/2.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.3.bam -ioutput_prefix=HG003_3_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/3.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.4.bam -ioutput_prefix=HG003_4_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/4.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.5.bam -ioutput_prefix=HG003_5_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/5.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.6.bam -ioutput_prefix=HG003_6_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/6.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.7.bam -ioutput_prefix=HG003_7_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/7.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.8.bam -ioutput_prefix=HG003_8_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/8.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.9.bam -ioutput_prefix=HG003_9_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/9.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.10.bam -ioutput_prefix=HG003_10_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/10.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.11.bam -ioutput_prefix=HG003_11_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/11.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.12.bam -ioutput_prefix=HG003_12_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/12.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.13.bam -ioutput_prefix=HG003_13_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/13.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.14.bam -ioutput_prefix=HG003_14_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/14.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.15.bam -ioutput_prefix=HG003_15_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/15.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.16.bam -ioutput_prefix=HG003_16_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/16.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.17.bam -ioutput_prefix=HG003_17_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/17.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.18.bam -ioutput_prefix=HG003_18_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/18.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.19.bam -ioutput_prefix=HG003_19_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/19.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.20.bam -ioutput_prefix=HG003_20_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/20.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.21.bam -ioutput_prefix=HG003_21_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/21.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.22.bam -ioutput_prefix=HG003_22_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/22.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.X.bam -ioutput_prefix=HG003_X_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/X.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.Y.bam -ioutput_prefix=HG003_Y_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/Y.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
dx run -y freebayes -isorted_bams=GIAB:/HG003/Illumina/Illumina_hg19_MatePair/HG003.mate_pair.sorted.MT.bam -ioutput_prefix=HG003_MT_hg19_bwa_mem_IlmnMatePair_FB -igenome_fastagz="Reference Genome Files:/H. Sapiens - GRCh37 - hs37d5 (1000 Genomes Phase II)/hs37d5.fa.gz" -igenotype_qualities=TRUE -itargets_bed="GIAB:/Workflow/Chromosome_bed_files/MT.bed" -istandard_filters=FALSE -iadvanced_options="-F 0.05 -m 0" --destination=/HG003/Illumina/Illumina_hg19_MatePair/FreeBayes_output/
